---
######## KUBERNETES INSTALL ######## 
- name: 'Download kubectl cli'
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.19.2/bin/linux/amd64/kubectl
    dest: /usr/local/bin/
  become: yes

- name: 'Add permitions'
  file:
    path: /usr/local/bin/kubectl
    mode: +x
  become: yes